# Generated by Django 3.0.5 on 2020-04-16 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificmeal',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals_id', to='orders.Order'),
        ),
        migrations.AddField(
            model_name='mealcategory',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='meals.Department'),
        ),
        migrations.AddField(
            model_name='meal',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='meals.MealCategory'),
        ),
    ]
